name: Linux Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install Curl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Build tix for linux
        env:
          TIX_INSTALL_PATH: out/tix
        run: ./gradlew install
      - name: Check output folder
        run: ls -la out